# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- bash: |
    export CURRENT=`git rev-parse HEAD`
    git config credential.$gitUrl.helper '!getPassword() { echo password=$accessToken; echo username=$username; }; getPassword'
    git push $gitUrl $CURRENT:refs/heads/master
  displayName: 'Push to Cloud Manager Git'
  env:
    gitUrl: $(https://github.com/Faizankhanabdul/devops-pipelines-poc.git)
    accessToken: $(b68ed1ecbec882e7a6d77787ccbaeb2e78899f50)
    username: $(Faizankhanabdul)
